// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createTicketStmt, err = db.PrepareContext(ctx, createTicket); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTicket: %w", err)
	}
	if q.getTicketByIdStmt, err = db.PrepareContext(ctx, getTicketById); err != nil {
		return nil, fmt.Errorf("error preparing query GetTicketById: %w", err)
	}
	if q.updateTicketStatusStmt, err = db.PrepareContext(ctx, updateTicketStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTicketStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createTicketStmt != nil {
		if cerr := q.createTicketStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTicketStmt: %w", cerr)
		}
	}
	if q.getTicketByIdStmt != nil {
		if cerr := q.getTicketByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTicketByIdStmt: %w", cerr)
		}
	}
	if q.updateTicketStatusStmt != nil {
		if cerr := q.updateTicketStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTicketStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createTicketStmt       *sql.Stmt
	getTicketByIdStmt      *sql.Stmt
	updateTicketStatusStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createTicketStmt:       q.createTicketStmt,
		getTicketByIdStmt:      q.getTicketByIdStmt,
		updateTicketStatusStmt: q.updateTicketStatusStmt,
	}
}
