# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/warehouse/tm_service/api/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from third_party.envoyproxy.validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from app.warehouse.tm_service.api import data_pb2 as tekone_dot_app_dot_warehouse_dot_tm__service_dot_api_dot_data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/warehouse/tm_service/api/api.proto',
  package='tekone.app.warehouse.tm_service.api',
  syntax='proto3',
  serialized_options=b'Z3go.tekoapis.com/tekone/app/warehouse/tm_service/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&app/warehouse/tm_service/api/api.proto\x12#tekone.app.warehouse.tm_service.api\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.tekone/app/warehouse/tm_service/api/data.proto\"n\n\x06Ticket\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x10\n\x08priority\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\")\n\x14GetTicketByIdRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\"X\n\x13\x43reateTicketRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\":\n\x14\x43reateTicketResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tticket_id\x18\x02 \x01(\t\">\n\x19UpdateTicketStatusRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"-\n\x1aUpdateTicketStatusResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8d\x04\n\tTmService\x12\xa5\x01\n\x0c\x43reateTicket\x12\x38.tekone.app.warehouse.tm_service.api.CreateTicketRequest\x1a\x39.tekone.app.warehouse.tm_service.api.CreateTicketResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/tm/create-ticket\x12\xbe\x01\n\x12UpdateTicketStatus\x12>.tekone.app.warehouse.tm_service.api.UpdateTicketStatusRequest\x1a?.tekone.app.warehouse.tm_service.api.UpdateTicketStatusResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/tm/update-ticket-status\x12\x96\x01\n\rGetTicketById\x12\x39.tekone.app.warehouse.tm_service.api.GetTicketByIdRequest\x1a+.tekone.app.warehouse.tm_service.api.Ticket\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/tm/get-ticketB5Z3go.tekoapis.com/tekone/app/warehouse/tm_service/apib\x06proto3'
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,tekone_dot_app_dot_warehouse_dot_tm__service_dot_api_dot_data__pb2.DESCRIPTOR,])




_TICKET = _descriptor.Descriptor(
  name='Ticket',
  full_name='tekone.app.warehouse.tm_service.api.Ticket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='tekone.app.warehouse.tm_service.api.Ticket.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tekone.app.warehouse.tm_service.api.Ticket.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='tekone.app.warehouse.tm_service.api.Ticket.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='tekone.app.warehouse.tm_service.api.Ticket.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='tekone.app.warehouse.tm_service.api.Ticket.priority', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='tekone.app.warehouse.tm_service.api.Ticket.status', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=292,
)


_GETTICKETBYIDREQUEST = _descriptor.Descriptor(
  name='GetTicketByIdRequest',
  full_name='tekone.app.warehouse.tm_service.api.GetTicketByIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='tekone.app.warehouse.tm_service.api.GetTicketByIdRequest.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=335,
)


_CREATETICKETREQUEST = _descriptor.Descriptor(
  name='CreateTicketRequest',
  full_name='tekone.app.warehouse.tm_service.api.CreateTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tekone.app.warehouse.tm_service.api.CreateTicketRequest.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='tekone.app.warehouse.tm_service.api.CreateTicketRequest.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='tekone.app.warehouse.tm_service.api.CreateTicketRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='priority', full_name='tekone.app.warehouse.tm_service.api.CreateTicketRequest.priority', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=425,
)


_CREATETICKETRESPONSE = _descriptor.Descriptor(
  name='CreateTicketResponse',
  full_name='tekone.app.warehouse.tm_service.api.CreateTicketResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tekone.app.warehouse.tm_service.api.CreateTicketResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='tekone.app.warehouse.tm_service.api.CreateTicketResponse.ticket_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=485,
)


_UPDATETICKETSTATUSREQUEST = _descriptor.Descriptor(
  name='UpdateTicketStatusRequest',
  full_name='tekone.app.warehouse.tm_service.api.UpdateTicketStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='tekone.app.warehouse.tm_service.api.UpdateTicketStatusRequest.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='tekone.app.warehouse.tm_service.api.UpdateTicketStatusRequest.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=549,
)


_UPDATETICKETSTATUSRESPONSE = _descriptor.Descriptor(
  name='UpdateTicketStatusResponse',
  full_name='tekone.app.warehouse.tm_service.api.UpdateTicketStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='tekone.app.warehouse.tm_service.api.UpdateTicketStatusResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=596,
)

DESCRIPTOR.message_types_by_name['Ticket'] = _TICKET
DESCRIPTOR.message_types_by_name['GetTicketByIdRequest'] = _GETTICKETBYIDREQUEST
DESCRIPTOR.message_types_by_name['CreateTicketRequest'] = _CREATETICKETREQUEST
DESCRIPTOR.message_types_by_name['CreateTicketResponse'] = _CREATETICKETRESPONSE
DESCRIPTOR.message_types_by_name['UpdateTicketStatusRequest'] = _UPDATETICKETSTATUSREQUEST
DESCRIPTOR.message_types_by_name['UpdateTicketStatusResponse'] = _UPDATETICKETSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ticket = _reflection.GeneratedProtocolMessageType('Ticket', (_message.Message,), {
  'DESCRIPTOR' : _TICKET,
  '__module__' : 'app.warehouse.tm_service.api.api_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.Ticket)
  })
_sym_db.RegisterMessage(Ticket)

GetTicketByIdRequest = _reflection.GeneratedProtocolMessageType('GetTicketByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTICKETBYIDREQUEST,
  '__module__' : 'app.warehouse.tm_service.api.api_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.GetTicketByIdRequest)
  })
_sym_db.RegisterMessage(GetTicketByIdRequest)

CreateTicketRequest = _reflection.GeneratedProtocolMessageType('CreateTicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETICKETREQUEST,
  '__module__' : 'app.warehouse.tm_service.api.api_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.CreateTicketRequest)
  })
_sym_db.RegisterMessage(CreateTicketRequest)

CreateTicketResponse = _reflection.GeneratedProtocolMessageType('CreateTicketResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATETICKETRESPONSE,
  '__module__' : 'app.warehouse.tm_service.api.api_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.CreateTicketResponse)
  })
_sym_db.RegisterMessage(CreateTicketResponse)

UpdateTicketStatusRequest = _reflection.GeneratedProtocolMessageType('UpdateTicketStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETICKETSTATUSREQUEST,
  '__module__' : 'app.warehouse.tm_service.api.api_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.UpdateTicketStatusRequest)
  })
_sym_db.RegisterMessage(UpdateTicketStatusRequest)

UpdateTicketStatusResponse = _reflection.GeneratedProtocolMessageType('UpdateTicketStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETICKETSTATUSRESPONSE,
  '__module__' : 'app.warehouse.tm_service.api.api_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.UpdateTicketStatusResponse)
  })
_sym_db.RegisterMessage(UpdateTicketStatusResponse)


DESCRIPTOR._options = None

_TMSERVICE = _descriptor.ServiceDescriptor(
  name='TmService',
  full_name='tekone.app.warehouse.tm_service.api.TmService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=599,
  serialized_end=1124,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTicket',
    full_name='tekone.app.warehouse.tm_service.api.TmService.CreateTicket',
    index=0,
    containing_service=None,
    input_type=_CREATETICKETREQUEST,
    output_type=_CREATETICKETRESPONSE,
    serialized_options=b'\202\323\344\223\002\032\022\030/api/v1/tm/create-ticket',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateTicketStatus',
    full_name='tekone.app.warehouse.tm_service.api.TmService.UpdateTicketStatus',
    index=1,
    containing_service=None,
    input_type=_UPDATETICKETSTATUSREQUEST,
    output_type=_UPDATETICKETSTATUSRESPONSE,
    serialized_options=b'\202\323\344\223\002!\022\037/api/v1/tm/update-ticket-status',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTicketById',
    full_name='tekone.app.warehouse.tm_service.api.TmService.GetTicketById',
    index=2,
    containing_service=None,
    input_type=_GETTICKETBYIDREQUEST,
    output_type=_TICKET,
    serialized_options=b'\202\323\344\223\002\027\022\025/api/v1/tm/get-ticket',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TMSERVICE)

DESCRIPTOR.services_by_name['TmService'] = _TMSERVICE

# @@protoc_insertion_point(module_scope)
