# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/warehouse/tm_service/api/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/warehouse/tm_service/api/data.proto',
  package='tekone.app.warehouse.tm_service.api',
  syntax='proto3',
  serialized_options=b'Z3go.tekoapis.com/tekone/app/warehouse/tm_service/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'app/warehouse/tm_service/api/data.proto\x12#tekone.app.warehouse.tm_service.api\"\x1a\n\x04\x44\x65mo\x12\x12\n\x04name\x18\x01 \x01(\tR\x04nameB5Z3go.tekoapis.com/tekone/app/warehouse/tm_service/apib\x06proto3'
)




_DEMO = _descriptor.Descriptor(
  name='Demo',
  full_name='tekone.app.warehouse.tm_service.api.Demo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tekone.app.warehouse.tm_service.api.Demo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['Demo'] = _DEMO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Demo = _reflection.GeneratedProtocolMessageType('Demo', (_message.Message,), {
  'DESCRIPTOR' : _DEMO,
  '__module__' : 'app.warehouse.tm_service.api.data_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.Demo)
  })
_sym_db.RegisterMessage(Demo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
