# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/warehouse/tm_service/api/event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/warehouse/tm_service/api/event.proto',
  package='tekone.app.warehouse.tm_service.api',
  syntax='proto3',
  serialized_options=b'Z3go.tekoapis.com/tekone/app/warehouse/tm_service/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(app/warehouse/tm_service/api/event.proto\x12#tekone.app.warehouse.tm_service.api\"#\n\x04Ping\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07message\x18\x02 \x01(\tB5Z3go.tekoapis.com/tekone/app/warehouse/tm_service/apib\x06proto3'
)




_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='tekone.app.warehouse.tm_service.api.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tekone.app.warehouse.tm_service.api.Ping.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='tekone.app.warehouse.tm_service.api.Ping.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['Ping'] = _PING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), {
  'DESCRIPTOR' : _PING,
  '__module__' : 'app.warehouse.tm_service.api.event_pb2'
  # @@protoc_insertion_point(class_scope:tekone.app.warehouse.tm_service.api.Ping)
  })
_sym_db.RegisterMessage(Ping)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
