// Code generated by tekit-gen-project. DO NOT EDIT.
package pubsub

import (
	"github.com/urfave/cli/v2"
	"go.tekoapis.com/tekone/app/warehouse/bff_service/config"
)

type pubsubInterface interface {
	Start(*cli.Context) error
}

type pubsubCore struct {
}

func newPubsubCore(cfg *config.Config) *pubsubCore {
	ps := &pubsubCore{}
	return ps
}

func (ps *pubsubCore) startSubscriber(errChan chan error, processes ...interface{}) {
}
