// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Tickets struct {
	TicketID uuid.UUID `json:"ticket_id"`
	UserID   uuid.UUID `json:"user_id"`
	Title    string    `json:"title"`
	Content  string    `json:"content"`
	Priority string    `json:"priority"`
	Status   string    `json:"status"`
}

type Users struct {
	UserID    uuid.UUID `json:"user_id"`
	FullName  string    `json:"full_name"`
	Username  string    `json:"username"`
	Gender    string    `json:"gender"`
	BirthDate time.Time `json:"birth_date"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
}
